"""Training subscriber for completed kernel-step events.

This module keeps prediction error, optimizer updates, and reflex-learning
signals out of the kernel step worker. It is opt-in: runtime code must subscribe
an instance to ``kernel.step.completed`` and provide events that contain the
in-process ``training_context`` generated by ``KernelEventWorker`` when training
is enabled.
"""

from __future__ import annotations

import random
from collections import deque
from dataclasses import dataclass, field
from typing import Deque

import torch

from models.events import BaseEvent
from tentacles.prediction_head import PredictionHead
from tentacles.spatial_memory_system import SpatialMemorySystem

from ..async_event_queue import AsyncEventQueue


@dataclass
class KernelTrainingObserver:
    """Opt-in subscriber that learns from completed kernel steps."""

    memory: SpatialMemorySystem
    predictor: PredictionHead | None = None
    error_threshold: float = 0.02
    lr: float = 5e-4
    enabled: bool = True
    error_buffer: Deque[float] = field(
        default_factory=lambda: deque(maxlen=64)
    )
    optimizer: torch.optim.Optimizer = field(init=False)
    reflex_log: list[dict[str, object]] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Create learner components without touching worker behavior."""

        device = self.memory.memory_field.device
        if self.predictor is None:
            self.predictor = PredictionHead(self.memory.channels)
        self.predictor.to(device)
        self.optimizer = torch.optim.Adam(
            self.predictor.parameters(),
            lr=self.lr,
        )

    def subscribe_to(
        self,
        queue: AsyncEventQueue,
    ) -> None:
        """Attach this observer to completed kernel-step events."""

        queue.subscribe("kernel.step.completed", self.handle_step_completed)

    async def handle_step_completed(
        self,
        event: BaseEvent,
    ) -> None:
        """React to ``kernel.step.completed`` without blocking runtime stepping setup."""

        if not self.enabled:
            return

        context = event.payload.get("training_context")
        if context is None:
            return

        self.learn_from_context(
            step_index=int(event.payload["step_index"]),
            context=context,
        )

    def learn_from_context(
        self,
        step_index: int,
        context: dict[str, torch.Tensor],
    ) -> dict[str, object]:
        """Run prediction-error training from one completed-step context."""

        active_state = context["active_state"].detach()
        visible_patch = context["visible_patch"].detach()
        next_position = context["next_position"].detach()
        velocity = context["velocity"].detach()
        next_patch = self.memory.read_patch(next_position).detach()

        predicted_next_patch = self.predictor(active_state, visible_patch)
        error = (predicted_next_patch - next_patch).pow(2).mean()
        error_value = float(error.detach().item())
        self.error_buffer.append(error_value)

        self.optimizer.zero_grad()
        error.backward()
        self.optimizer.step()

        reflex = error_value > self.error_threshold
        reflex_action = None
        if reflex:
            reflex_action = self.reflex_override(velocity)

        item = {
            "step": step_index,
            "error": error_value,
            "reflex": reflex,
            "reflex_action": _tensor_to_tuple(reflex_action),
        }
        self.reflex_log.append(item)
        return item

    def reflex_override(
        self,
        velocity: torch.Tensor,
    ) -> torch.Tensor:
        """Return a prototype reflex action derived from high prediction error."""

        mode = random.choice(["stop", "reverse", "random"])
        if mode == "stop":
            return torch.zeros_like(velocity)
        if mode == "reverse":
            return -velocity.clamp(min=-1, max=1)
        return torch.tensor(
            [random.choice([-1.0, 0.0, 1.0]) for _ in range(3)],
            device=velocity.device,
        )


def _tensor_to_tuple(
    value: torch.Tensor | None,
) -> tuple[float, ...] | None:
    """Convert an optional tensor to a compact log tuple."""

    if value is None:
        return None

    return tuple(float(item) for item in value.detach().cpu().tolist())
